### PR TITLE
CCRL Update (02-04/2023)

### PR DESCRIPTION
**Pull request by crippa1337**
* Updates a few engines
* Adds some more information in the header
* Adds a "Contributing" header

I was unsure what to write in the contributing header except just some general PR rules. Feel free to add or suggest something.

### CODE REVIEW

**Comment by cosmobobak** [comment]
Modified the wording of the last line in the README for clarity, does it express what you wish for it to?

**Comment by crippa1337** [comment]
Yes that's better 🙂. However, I added the "ratings are from single-CPU lists" part because I noticed Stash's rating was from the single-cpu which is around 90 elo lower than it's 4-CPU rating, this seems to hold for other engines as well such as BlackCore.

We need a consensus, since I think you've added Viri's 4-CPU rating now.

**Comment by cosmobobak** [comment]
Oh, i must have missed that, i didn't realise viri had been tested on 4CPU, i'll fix it.

**Comment by cosmobobak** [comment]
Ah - I haven't in fact done that. Viri's current ratings are from here
image
and here
image
neither of which are non-singlethreaded.

**Comment by cosmobobak** [comment]
yeah, great, tysm for the PR!

**Pull request merged**
